- hosts: sw-linux
  tasks:
  - name: deploy grub.conf (freebsd first)
    shell: |
        grub-set-default "FreeBSD"
        update-grub
  - name: "reboot host"
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

- hosts: sw-bsd
  gather_facts: no
  tasks:
  - name: "wait for freebsd"
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300

